### ISSUE TITLE
Unable to integrate with my Next.js Project

### ISSUE THREAD

**Issue by shahidwemtech** [1inch/limit-order-protocol-utils#20]
I need to know a few questions in order to integrate with my next.js project.

1. Do somebody have a working sample of reactjs/next.js/angular etc?
2. I am trying to use the following within my uniswap next.js project (With a new page) in order to create an order but failing

import {
  LimitOrderProtocolFacade, Web3ProviderConnector, LimitOrderBuilder, LimitOrderPredicateCallData
  , LimitOrderPredicateBuilder
} from '@1inch/limit-order-protocol'
import Web3 from 'web3'

const contractAddress = '0x7643b8c2457c1f36dc6e3b8f8e112fdf6da7698a';
const walletAddress = '0xd337163ef588f2ee7cdd30a3387660019be415c9';
const chainId = 1;

const web3 = new Web3(Web3.givenProvider) // since I am using uniswap, so it picks from there
    const connector = new Web3ProviderConnector(web3)

const limitOrderBuilder = new LimitOrderBuilder(
    contractAddress,
    chainId,
    connector
);

const limitOrder = limitOrderBuilder.buildLimitOrder({
    makerAssetAddress: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
    takerAssetAddress: '0x111111111117dc0aa78b770fa6a738034120c302',
    makerAddress: '0xfb3c7ebccccAA12B5A884d612393969Adddddddd',
    makerAmount: '100',
    takerAmount: '200',
    predicate: '0x0',
    permit: '0x0',
    interaction: '0x0',
});
const limitOrderTypedData = limitOrderBuilder.buildLimitOrderTypedData(
    limitOrder
);
const limitOrderSignature = limitOrderBuilder.buildOrderSignature(
    walletAddress,
    limitOrderTypedData
);
const limitOrderHash = limitOrderBuilder.buildLimitOrderHash(
    limitOrderTypedData
);

all of the above code runs successfully but do not show a popup for metamask until I do the following:

const limitOrderSignature = await limitOrderBuilder.buildOrderSignature(
      walletAddress,
      limitOrderTypedData
    );

But I am afraid that do I need to host my contract first? or the one provided by 1inch is sufficient?
Also, the limit-order-protocol-utils library is sufficient to just start off your project and do a limit order?

Thanks

**Comment by shoom3301** [comment]
Hey!
Yes, we are using this library in the Angular application.
You do not need to deploy your own contract, you can use an existing one (see README).
